### ISSUE TITLE
trajectory_analysis - error - clonocgraph is confusing

### ISSUE THREAD

**Issue by reJELIN** [bowmanr/scDNA#4]
Hello,

i'm testing your package with my data, it's a multi-sample composed of 2 samples.

When trying to make it works trajectory_analysis i get this error :

> sce<-trajectory_analysis(sce)
[1] "Building MDP"
[1] 27
[1] "Adding Weighted Edges"
[1] "Starting Optimization"
[1] "Finished Iteration: 5000"
[1] "Finished Iteration: 10000"
[1] "Finished Optimization"
[1] "Getting Mutation Paths/Policies"
[1] "tbl_df"     "tbl"        "data.frame"
 [1] "current_state"          "action_type"            "next_state"            
 [4] "reward"                 "Q_values"               "observed_states"       
 [7] "legal_action"           "total_actions"          "Probability_transition"
[10] "Q_values_normalized"   
[1] "Done with 1"
[1] "Done with 2"
[1] "Done with 3"
Error in V(net) : could not find function "V"

Do you know by any chance why ?

Also i'm kind of confuse by the clonograph

![Screenshot from 2023-11-08 15-25-23](https://github.com/bowmanr/scDNA/assets/112702898/0984aab3-b0e6-4bd0-b351-cd3bc2d63097)

I suppose I have 2 major clones subtypes  from what I understand ? one is ASLX1 WT and the other is ASXL1 Heterozygous, is that right ?

But what is Other and what is Complete ?

Thank you for your time and answer !

**Comment by namwob44** [comment]
Hi @reJELIN,

I was able to recreate the issue, it looks like the error is due to igraph. It should be fixed now, sorry about the trouble. First, please start a new R session. Then try the command:
remotes::install_github("bowmanr/scDNA", force = TRUE)

This will reinstall the package for you. Alternatively, you can specify the igraph library directly with library(igraph) before running the trajectory_analysis function.

Yes your understanding of ASLX1 WT and Heterozygous is correct. The "Complete" vs "Other" is our caller for if cells are completely genotyped or not. This is based on if the cells have "passed" the genotyping quality (GQ) and read Depth (DP), and Allele Frequency (AF) cutoffs selected earlier on in the workflow. If a cell is labeled as "Other" it means the Genotype Analysis Toolkit (GATK) made a genotype call, but that it failed at least one of these cutoffs.
